# Generated by Django 3.1 on 2020-10-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageFrom', models.IntegerField(blank=True, null=True)),
                ('ageTo', models.IntegerField(blank=True, null=True)),
                ('dayFrom', models.IntegerField(blank=True, null=True)),
                ('dayTo', models.IntegerField(blank=True, null=True)),
                ('gross', models.IntegerField(blank=True, null=True)),
                ('net', models.IntegerField(blank=True, null=True)),
                ('destination', models.IntegerField(blank=True, null=True)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
